### ISSUE TITLE
FSF seems to save all md that it analyzes

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#310] opened 2015-05-03 08:13 UTC
seen in https://github.com/fsprojects/Paket/pull/811

If this is correct it will break FsReveal and the KeepRunning stuff in ProjectScaffold

**Comment by matthid** [comment] 2015-05-03 09:14
I cannot see this: Added https://github.com/tpetricek/FSharp.Formatting/pull/309 (Which is a similar `WatchDocs` command) and it works fine.
It looks like the problem is self induced here: https://github.com/fsprojects/Paket/blob/master/docs/tools/generate.fsx#L6. I would recommend to wait for #309 to be merged and released and to implement it in the same way (which should be faster as well, spinning up a new process and re-compiling razor templates takes some time). This will work without even changing your current code.

Related (could catch you off-guard as well):
The only thing FSF does is checking the `.md` timestamps, if they are older than the generated `.html` file the `.md` file is ignored. So changing the razor templates will not trigger a new `html` generation. If you want to support template editing you probably want to delete all the output before.

**Closed** 2015-05-03 11:18 UTC
