### ISSUE TITLE
Generic types not displaying nicely

### ISSUE THREAD

**Issue by ovatsus** [tpetricek/FSharp.Formatting#138] opened 2014-02-24 13:00 UTC
http://fsharp.github.io/FSharp.Data/reference/fsharp-data-runtime-nameutils.html

![image](https://f.cloud.github.com/assets/738761/2245525/dc29d1c6-9d52-11e3-979f-d74e6d43e9ea.png)

This is what VS shows:
![image](https://f.cloud.github.com/assets/738761/2245553/96ed3b56-9d53-11e3-8d59-4931ee633559.png)

**Comment by ovatsus** [comment] 2015-03-23 12:35
Still repros on latest version

**Comment by tpetricek** [comment] 2015-04-20 11:21
Closing this as a duplicate of a more recent #269.

**Closed by tpetricek** 2015-04-20 11:21 UTC
