### ISSUE TITLE
Strange rendering of type parameters

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#269] opened 2015-02-27 09:29 UTC
![image](https://cloud.githubusercontent.com/assets/57396/6410048/61247e64-be6b-11e4-9b2e-817c75079af1.png)

Any ideas where I did something wrong?

**Comment by tpetricek** [comment] 2015-03-03 03:40
Eh, this happens when the type parameter name is automatically generated. I guess the recommendation is to add an explicit type annotation:

    let foo f a = f a // Generates ugly names for type parameters
    let bar f (a:'TInput) : 'TResult = f a // All are explicitly named

For some reason, the F# Compiler Service returns those ugly names instead of replacing them with acceptable `'a, 'b, 'c`.. as the IDE does. It would be nice to rename those in F# Formatting too, though...

**Comment by forki** [comment] 2015-03-03 06:50
So it's actually something that should be addressed in FCS?

**Comment by tpetricek** [comment] 2015-03-03 12:21
I would not call this FCS *bug* - if the intended behavior is to return ugly names, then that's fine :-). But FCS would be a logical place to improve this - and I don't think anybody would want to see the ugly internal IDs!

**Comment by matthid** [comment] 2015-03-23 17:08
Looks like a duplicate of https://github.com/tpetricek/FSharp.Formatting/issues/138

**Comment by tpetricek** [comment] 2015-04-20 13:50
I marked this as `up-for-grabs`. I suppose that we could probably implement automatic renaming of generated type parameters ourselves in F# Formatting as a workaround (although handling this in F# Compiler Service would be nicer).

**Comment by matthid** [comment] 2015-04-20 17:00
I just found https://github.com/tpetricek/FSharp.Formatting/issues/39, which seems to be related as well (but not exactly the same). Probably something to think about when fixing either of those issues.

**Comment by 7sharp9** [comment] 2015-10-29 10:59
I fixed some of these in FCS as it was bug there.

**Comment by ovatsus** [comment] 2015-12-21 01:55
Seems this is now fixed with latest version of both FCS and FF, so the issue can probably be closed

**Comment by tpetricek** [comment] 2016-01-12 15:47
Excellent news :)

**Closed by tpetricek** 2016-01-12 15:47 UTC
Labels: status-consider, type-feature, up-for-grabs
